# Generated by Django 2.0.1 on 2018-02-28 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180227_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('img', models.FileField(upload_to='nominees/img', verbose_name='Foto')),
                ('nominee_type', models.CharField(choices=[('D', 'Director'), ('M', 'Movie'), ('A', 'Actor'), ('S', 'Song')], max_length=1, verbose_name='Tipo')),
            ],
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='object_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('D', 'Director'), ('M', 'Movie'), ('A', 'Actor'), ('S', 'Song')], default='', max_length=1, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='nominee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Nominee'),
        ),
    ]
